services:
  build-frontend:
    image: genuine-oj/builder:latest
    build:
      context: .
      dockerfile: ./dockerfile/Dockerfile.build-frontend
    volumes:
       - ./data/frontend/:/root/frontend-dist/