FROM node:18

WORKDIR /root

ARG USE_MIRROR

RUN if [ "$USE_MIRROR" = "true" ]; then \
    git clone https://ghproxy.com/https://github.com/genuine-oj/frontend-naive.git frontend; \
    else \
    git clone https://github.com/genuine-oj/frontend-naive.git frontend; \
    fi

RUN cd frontend && yarn install --registry=https://registry.npmmirror.com

ADD ./config/build-frontend.sh .

CMD ["/bin/bash", "build-frontend.sh"]

ENTRYPOINT ["/bin/bash", "-c", "bash build-frontend.sh"]