FROM node:18

WORKDIR /root

RUN git clone https://github.com/genuine-oj/frontend-naive.git frontend

RUN cd frontend && yarn install --registry=https://registry.npmmirror.com

ADD ./config/build-frontend.sh .

CMD ["/bin/bash", "build-frontend.sh"]

ENTRYPOINT ["/bin/bash", "-c", "bash build-frontend.sh"]